@startuml
actor Trader
actor Administrateur

Trader --> (S'authentifier)
Trader --> (Ajouter un trade)
Trader --> (Modifier / Supprimer un trade)
Trader --> (Consulter les statistiques)
Trader --> (Taux de réussite, profit/perte, courbes d’évolution)
Trader --> (Comparaison des résultats selon la stratégie utilisée)
Trader --> (Exporter les données en PDF ou Excel)
Trader --> (Importer les données via MT5)
Trader --> (Ajouter une note ou capture d'écran)
Trader --> (Gérer le profil utilisateur)

Administrateur --> (Gérer les utilisateurs)
@enduml